services:
  postgres:
    image: postgres:latest
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: streaming_dev

networks:
  default:
    name: vex
